#!/bin/bash

ndo qutebrowser ${@}
#/usr/bin/dex ~/.local/share/applications/org.qutebrowser.qutebrowser.desktop ${@}
#/usr/bin/dex ~/.local/share/applications/firefox.desktop ${@}
#/usr/bin/chromium --incognito ${@}

exit 0
