#!/bin/bash

KEYDIRECTORY="$HOME/.openssl"

KEY="${KEYDIRECTORY}/$1"
FILE="$2"

openssl rsautl -inkey "$KEY" -decrypt < "$FILE"

# generate a 2048-bit RSA key and store it in key.txt
#openssl genrsa -out key.txt 2048
