#!/bin/bash

export MAIN_JS=scripts.js

if [[ -f ./_bin/build ]]; then
    
    ## Bundle Javascripts
    source ./_bin/bundlify

    ## UglifyJS
    source ./_bin/uglify
    
    ## Copy Javascripts
    find ./assets/js/ -type f ! -name '_*' -name '*.js' -exec cp {} ./public/assets/js/ \;
    
    exit 0
elif [[ -f ./build ]]; then

    ## Bundle Javascripts
    source ./bundlify

    ## UglifyJS
    source ./uglify
    
    ## Copy Javascripts
    find ../assets/js/ -type f ! -name '_*' -name '*.js' -exec cp {} ../public/assets/js/ \;

    exit 0
elif [[ -f ./uglify ]]; then

   source ./uglify

   exit 0
else

   echo 'Scripts not found: ./_bin/bundlify , ./_bin/uglify or uglify'
   exit 1

fi
