#!/bin/bash

update-packages
yay -S --repo --nocleanmenu --nodiffmenu --noeditmenu --mflags "--skippgpcheck" --needed ${@}
yay -S --aur --nocleanmenu --nodiffmenu --noeditmenu --mflags "--skippgpcheck" --needed ${@}

exit 0
