#!/bin/bash

sudo iptables -A TCP -p tcp -s 192.168.1.0/24 --dport 25 -j ACCEPT
sudo iptables -A UDP -p udp -s 192.168.1.0/24 --dport 25 -j ACCEPT

sudo ip6tables -A TCP -p tcp --dport 25 -j ACCEPT
sudo ip6tables -A UDP -p udp --dport 25 -j ACCEPT


exit 0
