#!/bin/bash

if is_privileged; then
    ${@}
    exit 0
fi



if [ $? = 0 ]; then

    /usr/bin/su - root -c "${@}" <<< $(/home/daniel/bin/kpass "KDEsu") &> /tmp/kdesu-msg
    if [ $? != 0 ]; then
        cat /tmp/kdesu-msg | /usr/bin/awk '{$1=""}1' | /usr/bin/sed -e 's/^[[:space:]]*//'
    fi
    
    /usr/bin/rm -f /tmp/kdesu-msg
else
    echo "cancelled"
fi

unset pass

exit 0
