#!/bin/bash

DEX=/usr/bin/dex



cd $HOME/.local/share/applications/



$DEX org.gajim.Gajim.desktop &

#$DEX claws-mail.desktop &
/home/daniel/bin/start-minimized email-cli Claws 2

#start-minimized linphone Linphone 7 &


PASS_STORES='dan/xmpp'

for pass_store in ${PASS_STORES}; do

    /home/daniel/bin/pass-get $pass_store <<< $(DISPLAY=:0.0 /usr/bin/kdialog --title "GPG" --password "You can enter your pin")
    
done



exit 0
